services:
  postgres:
    image: postgres:16
    container_name: plantshop_postgres
    environment:
      POSTGRES_USER: plantuser
      POSTGRES_PASSWORD: plantpass
      POSTGRES_DB: plantshop
    ports:
      - "5432:5432"
    volumes:
      - plantshop_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: plantshop_redis
    ports:
      - "6379:6379"

volumes:
  plantshop_pg:
